-- V0.2 MVP 初始 PostgreSQL 数据结构。
CREATE TABLE characters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    "desc" TEXT,
    strength INTEGER,
    agility INTEGER,
    intellect INTEGER,
    charisma INTEGER,
    stealth INTEGER,
    perception INTEGER,
    negotiation INTEGER,
    luck INTEGER,
    survival INTEGER,
    resist INTEGER,
    engineering INTEGER,
    medical INTEGER,
    melee_prof INTEGER,
    pistol_prof INTEGER,
    smg_prof INTEGER,
    shotgun_prof INTEGER,
    rifle_prof INTEGER,
    sniper_prof INTEGER,
    trait TEXT,
    fatigue INTEGER,
    stress INTEGER,
    injury TEXT,
    injury_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE weapon_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    category TEXT,
    hit INTEGER,
    damage INTEGER,
    penetration INTEGER,
    suppress INTEGER,
    ready INTEGER,
    ammo_per_round INTEGER,
    noise INTEGER,
    reliability INTEGER,
    close_mod INTEGER,
    mid_mod INTEGER,
    far_mod INTEGER,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    merchant_category TEXT,
    rep_requirement INTEGER
);

CREATE TABLE armor_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    type TEXT,
    protect INTEGER,
    coverage INTEGER,
    mobility INTEGER,
    initiative INTEGER,
    conceal INTEGER,
    anti_suppress INTEGER,
    "escape" INTEGER,
    max_durability INTEGER,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    merchant_category TEXT,
    rep_requirement INTEGER
);

CREATE TABLE consumable_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    "desc" TEXT,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    merchant_category TEXT,
    rep_requirement INTEGER
);

CREATE TABLE chest_rig_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    add_slots INTEGER,
    add_weight INTEGER,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    merchant_category TEXT,
    rep_requirement INTEGER
);

CREATE TABLE backpack_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    add_slots INTEGER,
    add_weight INTEGER,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    merchant_category TEXT,
    rep_requirement INTEGER
);

CREATE TABLE helmet_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    protect INTEGER,
    coverage INTEGER,
    mobility INTEGER,
    initiative INTEGER,
    conceal INTEGER,
    anti_suppress INTEGER,
    "escape" INTEGER,
    max_durability INTEGER,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    merchant_category TEXT,
    rep_requirement INTEGER
);

CREATE TABLE headset_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    hearing_level INTEGER,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    merchant_category TEXT,
    rep_requirement INTEGER
);

CREATE TABLE loot_item_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    category TEXT,
    "desc" TEXT,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    drop_weight INTEGER,
    merchant_category TEXT,
    rep_requirement INTEGER
);

CREATE TABLE loot_container_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    tags TEXT,
    value_tier INTEGER,
    search_risk INTEGER,
    search_time INTEGER,
    roll_min INTEGER,
    roll_max INTEGER
);

CREATE TABLE loot_container_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    container_id TEXT,
    item_category TEXT,
    weight INTEGER,
    min_quantity INTEGER,
    max_quantity INTEGER
);

CREATE TABLE node_container_defs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id TEXT,
    container_id TEXT,
    pool TEXT,
    count INTEGER,
    weight INTEGER
);

CREATE TABLE map_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    "desc" TEXT,
    start_node_id TEXT,
    extraction_node_id TEXT,
    tags TEXT
);

CREATE TABLE node_defs (
    id TEXT PRIMARY KEY,
    map_id TEXT,
    name TEXT,
    route_order INTEGER,
    explore_time INTEGER,
    distance TEXT,
    enemy_id TEXT,
    encounter_role TEXT,
    container_slots INTEGER,
    value_tier INTEGER,
    connections TEXT,
    tags TEXT
);

CREATE TABLE enemy_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    hp INTEGER,
    stress_threshold INTEGER,
    perception INTEGER,
    stealth INTEGER,
    agility INTEGER,
    weapon_id TEXT,
    armor_id TEXT,
    evasion INTEGER,
    mobility INTEGER,
    suppress INTEGER,
    backpack_container_id TEXT
);

CREATE TABLE event_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    "desc" TEXT,
    category TEXT,
    tags TEXT,
    exclusive_group TEXT,
    repeat_policy TEXT,
    options TEXT
);

CREATE TABLE event_bindings (
    id TEXT PRIMARY KEY,
    event_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    scope_id TEXT,
    phase TEXT NOT NULL,
    trigger_bp INTEGER,
    weight INTEGER,
    priority INTEGER,
    max_per_run INTEGER,
    cooldown_nodes INTEGER,
    enabled BOOLEAN
);

CREATE TABLE encounter_pool_entries (
    id TEXT PRIMARY KEY,
    map_id TEXT NOT NULL,
    role TEXT NOT NULL,
    enemy_id TEXT NOT NULL,
    weight INTEGER
);

CREATE TABLE merchant_defs (
    id TEXT PRIMARY KEY,
    name TEXT,
    category TEXT,
    reputation INTEGER,
    "desc" TEXT,
    open BOOLEAN,
    sort_order INTEGER
);

CREATE TABLE sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INTEGER,
    map_id TEXT,
    style TEXT,
    recovery_preset INTEGER,
    weapon_id TEXT,
    armor_id TEXT,
    consumables TEXT,
    status TEXT,
    seed BIGINT,
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    offline_limit_min INTEGER,
    total_runs INTEGER,
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE session_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER,
    run_index INTEGER,
    result TEXT,
    duration_min INTEGER,
    heat INTEGER,
    ammo_used INTEGER,
    injury TEXT,
    loot TEXT,
    report TEXT,
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE player_loadouts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INTEGER NOT NULL,
    weapon_id TEXT,
    armor_id TEXT,
    chest_rig_id TEXT,
    backpack_id TEXT,
    helmet_id TEXT,
    headset_id TEXT,
    consumables TEXT,
    preset_weapon_id TEXT,
    preset_armor_id TEXT,
    preset_chest_rig_id TEXT,
    preset_backpack_id TEXT,
    preset_helmet_id TEXT,
    preset_headset_id TEXT,
    preset_name TEXT,
    preset_consumables TEXT,
    preset2_weapon_id TEXT,
    preset2_armor_id TEXT,
    preset2_chest_rig_id TEXT,
    preset2_backpack_id TEXT,
    preset2_helmet_id TEXT,
    preset2_headset_id TEXT,
    preset2_name TEXT,
    preset2_consumables TEXT,
    preset3_weapon_id TEXT,
    preset3_armor_id TEXT,
    preset3_chest_rig_id TEXT,
    preset3_backpack_id TEXT,
    preset3_helmet_id TEXT,
    preset3_headset_id TEXT,
    preset3_name TEXT,
    preset3_consumables TEXT,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE inventories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT NOT NULL,
    name TEXT,
    kind TEXT,
    category TEXT,
    quantity INTEGER,
    price INTEGER,
    weight INTEGER,
    slots INTEGER,
    raid_extract BOOLEAN,
    merchant_category TEXT,
    rep_requirement INTEGER,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE armor_instances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    armor_id TEXT,
    max_durability INTEGER,
    cur_durability INTEGER,
    repair_count INTEGER,
    status TEXT
);

CREATE UNIQUE INDEX idx_encounter_pool ON encounter_pool_entries (map_id, role, enemy_id);
CREATE UNIQUE INDEX idx_player_loadouts_character_id ON player_loadouts (character_id);
CREATE UNIQUE INDEX idx_inv_src ON inventories (item_id, raid_extract);
CREATE INDEX idx_event_bindings_event_id ON event_bindings (event_id);
CREATE INDEX idx_event_bindings_scope_type ON event_bindings (scope_type);
CREATE INDEX idx_event_bindings_scope_id ON event_bindings (scope_id);
CREATE INDEX idx_event_bindings_phase ON event_bindings (phase);
CREATE INDEX idx_loot_container_rules_container_id ON loot_container_rules (container_id);
CREATE INDEX idx_node_container_defs_node_id ON node_container_defs (node_id);
CREATE INDEX idx_node_container_defs_container_id ON node_container_defs (container_id);
CREATE INDEX idx_node_container_defs_pool ON node_container_defs (pool);
