-- 地图系统 v2：节点坐标、独立边和独立撤离点。
ALTER TABLE map_defs ADD COLUMN layout_columns INTEGER NOT NULL DEFAULT 1;
ALTER TABLE map_defs ADD COLUMN layout_rows INTEGER NOT NULL DEFAULT 1;
ALTER TABLE node_defs ADD COLUMN position_x INTEGER NOT NULL DEFAULT 0;
ALTER TABLE node_defs ADD COLUMN position_y INTEGER NOT NULL DEFAULT 0;

CREATE TABLE map_edge_defs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id TEXT NOT NULL,
    from_node_id TEXT NOT NULL,
    to_node_id TEXT NOT NULL,
    move_time INTEGER NOT NULL,
    bidirectional BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE extraction_point_defs (
    id TEXT PRIMARY KEY,
    map_id TEXT NOT NULL,
    name TEXT,
    kind TEXT,
    anchor_node_id TEXT NOT NULL,
    travel_time INTEGER,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    icon_key TEXT,
    tags TEXT
);

CREATE UNIQUE INDEX idx_map_edge ON map_edge_defs (map_id, from_node_id, to_node_id);
CREATE INDEX idx_map_edge_defs_map_id ON map_edge_defs (map_id);
CREATE INDEX idx_extraction_point_defs_map_id ON extraction_point_defs (map_id);
CREATE INDEX idx_extraction_point_defs_anchor_node_id ON extraction_point_defs (anchor_node_id);
