-- V1.2 敌人模板表：替代写死 enemy_defs 的运行时生成配置。
CREATE TABLE enemy_template_defs (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL DEFAULT 'grunt',
    spawn_tags TEXT DEFAULT '[]',
    tier INTEGER NOT NULL DEFAULT 0,
    hp_base INTEGER NOT NULL DEFAULT 60,
    hp_flux INTEGER NOT NULL DEFAULT 10,
    hp_floor INTEGER NOT NULL DEFAULT 30,
    hp_cap INTEGER NOT NULL DEFAULT 400,
    stress_base INTEGER NOT NULL DEFAULT 50,
    stress_flux INTEGER NOT NULL DEFAULT 8,
    stress_floor INTEGER NOT NULL DEFAULT 20,
    stress_cap INTEGER NOT NULL DEFAULT 300,
    perception_base INTEGER NOT NULL DEFAULT 30,
    perception_flux INTEGER NOT NULL DEFAULT 5,
    stealth_base INTEGER NOT NULL DEFAULT 30,
    stealth_flux INTEGER NOT NULL DEFAULT 5,
    agility_base INTEGER NOT NULL DEFAULT 30,
    agility_flux INTEGER NOT NULL DEFAULT 5,
    evasion_base INTEGER NOT NULL DEFAULT 10,
    evasion_flux INTEGER NOT NULL DEFAULT 3,
    mobility_base INTEGER NOT NULL DEFAULT 0,
    mobility_flux INTEGER NOT NULL DEFAULT 2,
    suppress_base INTEGER NOT NULL DEFAULT 10,
    suppress_flux INTEGER NOT NULL DEFAULT 3,
    weapon_pool TEXT DEFAULT '[]',
    armor_pool TEXT DEFAULT '[]',
    ammo_level_min INTEGER NOT NULL DEFAULT 1,
    ammo_level_max INTEGER NOT NULL DEFAULT 4,
    ammo_rounds_base INTEGER NOT NULL DEFAULT 20,
    ammo_rounds_mult REAL NOT NULL DEFAULT 1.0,
    backpack_pool TEXT DEFAULT '[]',
    boss_loot_items TEXT DEFAULT '[]',
    boss_ammo_drop INTEGER NOT NULL DEFAULT 0,
    boss_weapon_id TEXT NOT NULL DEFAULT '',
    boss_armor_id TEXT NOT NULL DEFAULT '',
    boss_name TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_enemy_template_kind ON enemy_template_defs (kind, tier, sort_order);